spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_code
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.msb.pojo
  mapper-locations: classpath:com/msb/mapper/*.xml